uncommenting running of tests for pre-push

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -8,12 +8,12 @@ if [ $? -ne 0 ]; then
 fi
 
 
-# npm run test # Run tests
+npm run test # Run tests
 
-# if [ $? -ne 0 ]; then
-#   echo "[TEST ERROR] Test must pass before pushing to origin."
-#   exit 1
-# fi
+if [ $? -ne 0 ]; then
+  echo "[TEST ERROR] Test must pass before pushing to origin."
+  exit 1
+fi
 
 
 # Add more checks here
